spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contract?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Yt770921

server:
  port: 8080

actable:
  table:
    auto: update
  model:
    pack: com.yutian.contract.entity
  database:
    type: mysql
